name: Terraform VPC Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to destroy (dev, stage, main)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: Destroy Terraform Environment
    runs-on: ubuntu-latest

    env:
      TF_LOG: INFO
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-terraform-destroy
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -no-color -input=false -var-file="environments/${{ env.ENVIRONMENT }}/terraform.tfvars"

      - name: Terraform Destroy Confirmation
        run: |
          echo "⚠️ WARNING: You are about to destroy the '${{ env.ENVIRONMENT }}' environment!"
          echo "Sleeping for 10 seconds to allow cancellation..."
          sleep 10

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -var-file="environments/${{ env.ENVIRONMENT }}/terraform.tfvars"
