name: Terraform VPC Deployment

on:
  push:
    branches:
      - main
      - dev
      - stage
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy (dev, stage, main)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      TF_LOG: INFO
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-terraform
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -var-file="environments/${{ env.ENVIRONMENT }}/terraform.tfvars"

      - name: Terraform Apply
        if: |
          github.event_name == 'workflow_dispatch' ||
          github.ref == 'refs/heads/${{ env.ENVIRONMENT }}'
        run: terraform apply -auto-approve -input=false -var-file="environments/${{ env.ENVIRONMENT }}/terraform.tfvars"
