name: VPC Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev/stage/prod)'
        required: true
        default: 'dev'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

jobs:
  terraform-vpc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-terraform-vpc
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Clean Terraform
        working-directory: ./terraform/vpc
        run: rm -rf .terraform

      - name: Terraform Init
        working-directory: ./terraform/vpc
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.AWS_S3_BUCKET }}" \
            -backend-config="key=vpc/${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.DYNAMODB_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Terraform Plan
        working-directory: ./terraform/vpc
        run: |
          terraform plan -var-file="environments/${{ github.event.inputs.environment }}/terraform.tfvars" -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform/vpc
        run: terraform apply -auto-approve tfplan
