name: Terraform VPC Deployment

on:
  # push:
  #   branches:
  #     - main
  #     - dev
  #     - stage 
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy (dev, stage, main)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
      ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-terraform
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init (Reconfigure Backend)
        run: |
          echo "Using S3 bucket: ${{ env.AWS_S3_BUCKET }}"
          terraform init -reconfigure \
            -backend-config="bucket=${{ env.AWS_S3_BUCKET }}" \
            -backend-config="key=aws-vpc/${{ env.ENVIRONMENT }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.DYNAMODB_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Terraform Workspace
        run: |
          terraform workspace list || true
          terraform workspace select ${{ env.ENVIRONMENT }} || terraform workspace new ${{ env.ENVIRONMENT }}

      - name: Terraform Plan
        run: terraform plan -no-color -input=false -var-file="environments/${{ env.ENVIRONMENT }}/terraform.tfvars"

      - name: Terraform Apply
        if: always()
        run: terraform apply -auto-approve -input=false -var-file="environments/${{ env.ENVIRONMENT }}/terraform.tfvars"
